webtalk_init -webtalk_dir C:\\Users\\E.Marte\\Documents\\GitHub\\Marte_Fpga\\ArtyS7MarteReview\\WrittingToLeds\\Review_01.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-08-16 15:34:42" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211451298_1777532808_0_606" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "h84biarjb7o7nu66sve5h6n8o3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2691 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.457 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1534447833274" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key Arch -value "spartan7" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key Device -value "7s50" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1534447833274"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key DebugCount -value "1" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1534448082759"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1534448082759"
webtalk_transmit -clientid 637429934 -regid "211451298_1777532808_0_606" -xml C:\\Users\\E.Marte\\Documents\\GitHub\\Marte_Fpga\\ArtyS7MarteReview\\WrittingToLeds\\Review_01.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\E.Marte\\Documents\\GitHub\\Marte_Fpga\\ArtyS7MarteReview\\WrittingToLeds\\Review_01.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\E.Marte\\Documents\\GitHub\\Marte_Fpga\\ArtyS7MarteReview\\WrittingToLeds\\Review_01.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
